# Site settings
title:       Robert Martinez
email:       robert.david.martinez@gmail.com
author:      Robert Martinez
description: "A meticulously neglected blog"
baseurl:     ""
url:         "/"

# Google analytics
google_analytics: UA-65365742-1

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true
show_social_icons:  false
# show_comments:      true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: RobertMartinez
stackoverflow_id:
twitter_username: soggypenny
google_plus_id:
linkedin_username: rdmartinez
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /blog/:title
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
